project:
  type: website
  resources:
    - "*.xlsx"
    - "*.pptx"
    - "*.pdf"

website:
  title: "SYP's MTU Trading Room 2024"
  image: "syp_logo.jpg"
  favicon: "fav.png"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
#      - about.qmd                  # this adds the acknowledgements page to navbar
#      - posts.qmd                  # adds instructor blog posts link to navbar
      - sposts.qmd                  # adds student blog posts link to navbar
#     - href: plan_24.qmd
#       text: Planning Materials
      - href: resources.qmd
        text: Resources
      - href: calculators.qmd
        text: Calculators
  page-navigation: true

  page-footer:
        left: "Copyright 2025, Daniel J. Green. All Rights Reserved."
        right: "Korea & Japan Trip 2025"
  reader-mode: true

  sidebar:
    style: "docked"
    search: true
    logo: "images/syp_logo.jpg"
    contents:
        - section: "Front Page"
          contents:
            - index.qmd
            - text: "---"
        - section: "Schedule"
          contents:
            - schedule.qmd
            - text: "---"
        - section: "Friday 10/24/25"
          contents:
            - 1024_obj.qmd
            - text: "---"
        - section: "Saturday 10/25/25"
          contents:
            - 1025_obj.qmd
#            - notes_tues.qmd
            - text: "---"
        - section: "Sunday 10/26/25"
          contents:
            - 1026_obj.qmd
#            - notes_10_26.qmd
            - text: "---"
        - section: "Monday 10/27/25"
          contents:
            - 1027_obj.qmd
#            - notes_10_27.qmd
            - text: "---"
        - section: "Tuesday 10/28/25"
          contents:
            - 1028_obj.qmd
#           - notes_10_28.qmd
            - text: "---"
        - section: "Wednesday 10/29/25"
          contents:
            - 1029_obj.qmd
#           - notes_10_29.qmd
            - text: "---"
        - section: "Thursday 10/30/25"
          contents:
            - 1030_obj.qmd
#           - notes_10_28.qmd
            - text: "---"
        - section: "Friday 10/31/25"
          contents:
#            - 1031_obj.qmd
            - text: "---"
        - section: "Saturday 11/01/25"
          contents:
#            - 1101_obj.qmd
            - text: "---"
        - section: "Sunday 11/02/25"
          contents:
#            - 1102_obj.qmd
            - text: "---"
        - section: "Monday 11/03/25"
          contents:
#            - 1103_obj.qmd
            - text: "---"
        - section: "Tuesday 11/04/25"
          contents:
#            - 1104_obj.qmd
            - text: "---"
        - section: "Wednesday 11/05/25"
          contents:
#            - 1105_obj.qmd
            - text: "---"
        - section: "Thursday 11/06/25"
          contents:
#            - 1106_obj.qmd
            - text: "---"
        - section: "Friday 11/07/25"
          contents:
#            - 1107_obj.qmd
            - text: "---"
        - section: "Saturday 11/08/25"
          contents:
#            - 1108_obj.qmd
            - text: "---"
        - section: "Sunday 11/09/25"
          contents:
#            - 1109_obj.qmd
            - text: "---"
        - section: "Monday 11/10/25"
          contents:
#            - 1110_obj.qmd
            - text: "---"
        - section: "Tuesday 11/11/25"
          contents:
#            - 1111_obj.qmd
            - text: "---"
        - section: "Wednesday 11/12/25"
          contents:
#            - 1112_obj.qmd
            - text: "---"
        - section: "Thursday 11/13/25"
          contents:
#            - 1113_obj.qmd
            - text: "---"
        - section: "Friday 11/14/25"
          contents:
#            - 1114_obj.qmd
            - text: "---"
        - section: "Saturday 11/15/25"
          contents:
#            - 1115_obj.qmd
            - text: "---"

render:
    - index.qmd
    - about.qmd



format:
  html:
    theme: lux
    css:
    - styles.css
    - custom.css
    - custom.js
    toc: true

editor: visual

