project:
  type: website
  resources:
    - "*.xlsx"
    - "*.pptx"
    - "*.pdf"

website:
  title: "Korea & Japan Trip 2025"
  favicon: "fav.png"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: posts.qmd
        text: Things to SEE & DO
      - href: sposts.qmd
        text: Blog
      - href: resources.qmd
        text: Resources
      - href: korea_trip_full_itinerary.qmd
        text: Korea Trip Overview
      - href: japan_visual_itin.qmd
        text: Japan SCHEDULE
  page-navigation: true
  page-footer:
    left: "Copyright 2025, Daniel J. Green. All Rights Reserved."
    right: "Korea & Japan Trip 2025"
  reader-mode: true

  sidebar:
    style: "docked"
    search: true
    logo: "images/mt_fuji.jpg"
    collapse-level: 2
    pinned: true
    contents:
      - section: "Front Page"
        contents:
          - index.qmd
      - text: "---"
      - section: "Trip Overviews"
        contents:
          - korea_trip_full_itinerary.qmd
          - japan_trip_full_itinerary.qmd
      - text: "---"
      - section: "Trip Research"
        contents:
          - korea_trip_questions.qmd
          - korean_food.qmd
          - japan_food.qmd
      - text: "---"
      - section: "Schedule"
        contents:
          - schedule.qmd
          - preliminary_schedule.qmd
      - text: "---"
      - section: "Friday 10/24/25"
        contents:
          - 1024_obj.qmd
        - text: "---"
        - section: "🇰🇷 Korea Trip - Day 1 (Oct 24)"
          contents:
            - daily_itineraries/October_24_Day_1.qmd
            - notes/notes_10_24.qmd
            - text: "---"
        - section: "🇰🇷 Korea Trip - Day 2 (Oct 25)"
          contents:
            - daily_itineraries/October_25_Day_2.qmd
            - notes/notes_10_25.qmd
            - text: "---"
        - section: "🇰🇷 Korea Trip - Day 3 (Oct 26)"
          contents:
            - daily_itineraries/October_26_Day_3.qmd
            - notes/notes_10_26.qmd
            - text: "---"
        - section: "🇰🇷 Korea Trip - Day 4 (Oct 27)"
          contents:
            - daily_itineraries/October_27_Day_4.qmd
            - notes/notes_10_27.qmd
            - text: "---"
        - section: "🇰🇷 Korea Trip - Day 5 (Oct 28)"
          contents:
            - daily_itineraries/October_28_Day_5.qmd
            - notes/notes_10_28.qmd
            - text: "---"
        - section: "🇰🇷 Korea Trip - Day 6 (Oct 29)"
          contents:
            - daily_itineraries/October_29_Day_6.qmd
            - notes/notes_10_29.qmd
            - text: "---"
        - section: "🇰🇷 Korea Trip - Day 7 (Oct 30)"
          contents:
            - daily_itineraries/October_30_Day_7.qmd
            - notes/notes_10_30.qmd
            - text: "---"
        - section: "🇰🇷 Korea Trip - Day 8 (Oct 31)"
          contents:
            - daily_itineraries/October_31_Day_8.qmd
            - notes/notes_10_31.qmd
            - text: "---"
        - section: "🇯🇵 Japan Trip - Day 1 (Nov 2)"
          contents:
            - daily_itineraries/November_2_Day_1.qmd
            - notes/notes_11_02.qmd
            - text: "---"
        - section: "🇯🇵 Japan Trip - Day 2 (Nov 3)"
          contents:
            - daily_itineraries/November_3_Day_2.qmd
            - notes/notes_11_03.qmd
            - text: "---"
        - section: "🇯🇵 Japan Trip - Day 3 (Nov 4)"
          contents:
            - daily_itineraries/November_4_Day_3.qmd
            - notes/notes_11_04.qmd
            - text: "---"
        - section: "🇯🇵 Japan Trip - Day 4 (Nov 5)"
          contents:
            - daily_itineraries/November_5_Day_4.qmd
            - notes/notes_11_05.qmd
            - text: "---"
        - section: "🇯🇵 Japan Trip - Day 5 (Nov 6)"
          contents:
            - daily_itineraries/November_6_Day_5.qmd
            - notes/notes_11_06.qmd
            - text: "---"
        - section: "🇯🇵 Japan Trip - Day 6 (Nov 7)"
          contents:
            - daily_itineraries/November_7_Day_6.qmd
            - notes/notes_11_07.qmd
            - text: "---"
        - section: "🇯🇵 Japan Trip - Day 7 (Nov 8)"
          contents:
            - daily_itineraries/November_8_Day_7.qmd
            - notes/notes_11_08.qmd
            - text: "---"
        - section: "🇯🇵 Japan Trip - Day 8 (Nov 9)"
          contents:
            - daily_itineraries/November_9_Day_8.qmd
            - notes/notes_11_09.qmd
            - text: "---"
        - section: "🇯🇵 Japan Trip - Day 9 (Nov 10)"
          contents:
            - daily_itineraries/November_10_Day_9.qmd
            - notes/notes_11_10.qmd
            - text: "---"
        - section: "🇯🇵 Japan Trip - Day 10 (Nov 11)"
          contents:
            - daily_itineraries/November_11_Day_10.qmd
            - notes/notes_11_11.qmd
            - text: "---"
        - section: "🇯🇵 Japan Trip - Day 11 (Nov 12)"
          contents:
            - daily_itineraries/November_12_Day_11.qmd
            - notes/notes_11_12.qmd
            - text: "---"
        - section: "🇯🇵 Japan Trip - Day 12 (Nov 13)"
          contents:
            - daily_itineraries/November_13_Day_12.qmd
            - notes/notes_11_13.qmd
            - text: "---"
        - section: "🇯🇵 Japan Trip - Day 13 (Nov 14)"
          contents:
            - daily_itineraries/November_14_Day_13.qmd
            - notes/notes_11_14.qmd
            - text: "---"
        - section: "🇯🇵 Japan Trip - Day 14 (Nov 15)"
          contents:
            - daily_itineraries/November_15_Day_14.qmd
            - notes/notes_11_15.qmd
            - text: "---"

format:
  html:
    theme: lux
    toc: true

editor: visual
