---
title: "Korea & Japan 2025 Schedule at a Glance"
author: "Dan Green"
date: 09/03/25
editor: visual
---

# Schedule at a Glance

# Schedule at a Glance

+----------------------+----------------------+---------------------+--------------------------------+--------------------------------+--------------------------------+----------------------+
| Sunday               | Monday               | Tuesday             | Wednesday                      | Thursday                       | Friday                         | Saturday             |
+======================+======================+=====================+================================+================================+================================+======================+
|                      |                      |                     |                                |                                | **Oct 24**                     | **Oct. 25**          |
|                      |                      |                     |                                |                                |                                |                      |
|                      |                      |                     |                                |                                | Fly to Korea!                  | Arrive Incheon       |
+----------------------+----------------------+---------------------+--------------------------------+--------------------------------+--------------------------------+----------------------+
| **Oct. 26**          | **Oct. 27**          | **Oct. 28**         | **Oct. 29**                    | **Oct. 30**                    | **Oct. 31**                    | **Nov. 1**           |
|                      |                      |                     |                                |                                |                                |                      |
| Incheon              | N. Seoul (Insadong)  | N. Seoul (Insadong) | Seoul                          | Seoul                          | Start day in Seoul             | Tokyo                |
|                      |                      |                     |                                |                                |                                |                      |
| Korean War           | DMZ                  | Korean Culture      | Temple Stay                    | Shopping                       | End Day in Tokyo               | Catch Breath!        |
|                      |                      |                     |                                |                                |                                |                      |
|                      |                      |                     |                                |                                | Fly to Tokyo                   | Hotel East 21 Tokyo  |
|                      |                      |                     |                                |                                |                                |                      |
|                      |                      |                     |                                |                                | Hotel East 21 Tokyo            |                      |
+----------------------+----------------------+---------------------+--------------------------------+--------------------------------+--------------------------------+----------------------+
| **Nov. 2**           | **Nov. 3**           | **Nov. 4**          | **Nov. 5**                     | **Nov. 6**                     | **Nov. 7**                     | **Nov. 8**           |
|                      |                      |                     |                                |                                |                                |                      |
| TD #1                | TD #2                | TD #3               | TD #4                          | TD #5                          | TD #6                          | TD #7                |
|                      |                      |                     |                                |                                |                                |                      |
| Tokyo                | Tokyo                | Tokyo               | Tokyo                          | Start day in Tokyo             | Start day in Mt. Fuji Area     | Kyoto                |
|                      |                      |                     |                                |                                |                                |                      |
| Tour Starts          | Hotel East 21 Tokyo  | Luggage to Kyoto    | Hotel East 21 Tokyo            | End Day in Mt. Fuji Area       | Bullet Train to Kyoto          | Hotel Princess Kyoto |
|                      |                      |                     |                                |                                |                                |                      |
| Welcome Dinner       |                      | Hotel East 21 Tokyo |                                | Hotel Regina                   | End Day in Kyoto               |                      |
|                      |                      |                     |                                |                                |                                |                      |
| Hotel East 21 Tokyo  |                      |                     |                                | (No Luggage)                   | Hotel Princess Kyoto           |                      |
+----------------------+----------------------+---------------------+--------------------------------+--------------------------------+--------------------------------+----------------------+
| **Nov. 9**           | **Nov. 10**          | **Nov. 11**         | **Nov. 12**                    | **Nov. 13**                    | **Nov. 14**                    | **Nov. 15**          |
|                      |                      |                     |                                |                                |                                |                      |
| TD #8                | TD #9                | TD #10              | TD#11                          | TD #12                         | TD #13                         | TD #14               |
|                      |                      |                     |                                |                                |                                |                      |
| Kyoto                | Kyoto                | Start day in Kyoto  | Start day in Niigata           | Tokyo                          | Tokyo                          | Tokyo                |
|                      |                      |                     |                                |                                |                                |                      |
| Hotel Princess Kyoto | (Luggage to Tokyo)   | Fly to Niigata      | Bullet Train to Tokyo          | Hotel Grand Niiko Odaiba Tokyo | Hotel Grand Niiko Odaiba Tokyo | Fly Home!            |
|                      |                      |                     |                                |                                |                                |                      |
|                      | Hotel Princess Kyoto | End day in Niigata  | End day in Tokyo               |                                |                                |                      |
|                      |                      |                     |                                |                                |                                |                      |
|                      |                      | Hotel Nikko Niigata | Hotel Grand Niiko Odaiba Tokyo |                                |                                |                      |
|                      |                      |                     |                                |                                |                                |                      |
|                      |                      | (No Luggage)        |                                |                                |                                |                      |
+----------------------+----------------------+---------------------+--------------------------------+--------------------------------+--------------------------------+----------------------+

: Korea & Japan Schedule at a Glance

## Reference Material

[Wisconsin Quilt Museum Itinerary](https://www.wiquiltmuseum.com/products/japan-trip-nov-2025-heidi-parkes-final-payment)
